# Header
menu:
  归档: /archives
rss: /atom.xml
title: "Banana Y.X."

author: "Banana Y.X."
aboutme: 面朝大海，春暖花开。

# Content
excerpt_link: 全文...
fancybox: true
date_format: 'YYYY年MM月DD日'

socials:
  github: "https://github.com/Bananayx"
  email: "xiaoyi9289@outlook.com"
  wechat: "weixinqq_3956094132"


# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: 'UA-61220413-1'
gauges_analytics:
favicon: https://img.cdn1.vip/i/6891ccaa59734_1754385578.webp
avatar: "https://img.cdn1.vip/i/6891ccaa59734_1754385578.webp"
twitter:
google_plus:
fb_admins:
fb_app_id:
